In [1]:
Import numpy as np

SyntaxError: invalid syntax (<ipython-input-1-5f8f38d20256>, line 1)

In [2]:
import numpy as np

In [3]:
list=[1,2,3]

In [4]:
#list ko array mei convert kar diya

In [5]:
array=np.array(list)

In [6]:
array

array([1, 2, 3])

In [7]:
#multi D array k liye nested list ko array mei convert karenge

In [8]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#range use karke array banana

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
# array of zero k liye np.zeroes use karenge. agar ek value denge to 1D banega 

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
#matrix of zero k liye row and coloumn pass karna hoga tuple mei

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
# agar array of 1 chahiye toh ones likh denge

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# linspace(start,stop,third argument) evenly space array from start to stop

In [21]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
# isne 0 se 5 tak 10 evenly space values di in array

In [23]:
#identity matrix

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
#to create array of random no

In [26]:
np.random.rand(5)

array([0.7368447 , 0.81521271, 0.31305027, 0.46233576, 0.36542295])

In [27]:
#matrix k liye row coloum dena padega

In [28]:
np.random.rand(5,5)

array([[0.17287136, 0.07897603, 0.89361824, 0.46311065, 0.86172929],
       [0.00543339, 0.26708701, 0.50842566, 0.01506538, 0.08647755],
       [0.11663617, 0.85578683, 0.64875508, 0.94037493, 0.78286782],
       [0.08353008, 0.04103864, 0.74398869, 0.51701289, 0.5941848 ],
       [0.1653106 , 0.29697694, 0.56565567, 0.57914274, 0.20433275]])

In [29]:
np.random.randn(2)

array([-0.58296342, -2.02550974])

In [30]:
np.random.randn(4,4)

array([[ 1.13385862, -0.13703103, -0.50849095,  0.32419672],
       [ 1.91516163, -1.30667081,  0.83183555, -0.06208715],
       [ 1.72988247,  0.12836067, -0.6228116 , -0.18523274],
       [-0.62146978, -0.14321779, -1.17055399,  1.26856883]])

In [31]:
#randint(low,high) range k beech ka ek no dega

In [32]:
np.random.randint(1,100)

73

In [33]:
#agar array of random integers in a range chahiye toh

In [34]:
np.random.randint(1,100,10)

array([43, 63,  6, 80, 48, 83, 87, 23, 60, 67])

In [35]:
#reshape is used to conevrt an array into matrix of our desired rows and coloumns

In [36]:
arr=np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
#agar hum 5 row aur 10 coloumn denge toh error aayega kyuki humare pass 25 nos hi hai aur 5*10 ki matrix k liye 50 no chahaiye

In [40]:
# max() and min() gives max and min value

In [41]:
arr.max()

24

In [42]:
arr.min()

0

In [43]:
# agar index chahaiye max aur min value ka toh argmax() and argmin() use karenge

In [44]:
arr=np.random.randint(5,50,10)

In [45]:
arr

array([ 5, 30, 46, 39, 27,  9, 15, 35, 44, 21])

In [46]:
arr.argmax()

2

In [47]:
arr.argmin()

0

In [48]:
# shape tells what is the shape i.e array, matrix, etc

In [49]:
arr.shape

(10,)

In [50]:
# 10 means array of 10 elements 

In [51]:
arr=arr.reshape(2,5)

In [52]:
arr

array([[ 5, 30, 46, 39, 27],
       [ 9, 15, 35, 44, 21]])

In [53]:
arr.shape

(2, 5)

In [54]:
# (2,5) means matrix with 2 rows and 5 coloumns

In [55]:
# dtype gives the data type

In [56]:
arr.dtype

dtype('int32')

In [57]:
# it means arr is a 32 bit integer