In [2]:
import numpy as np

In [3]:
arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [17]:
#array slicing is similar to list slicing

In [11]:
arr[0:5]=100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
#this means start from index 0 and upto index 5 replace everything with 100.
#this is BROADCASTING

In [19]:
arr=np.arange(0,11)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
slice_of_array=arr[0:6]

In [22]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [23]:
slice_of_array[:]=99

In [24]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
#we can notice that change has occured in original array as well. This means that data is not copied.
#it is just another view or partial view of the original array. any change will be reflected back.
# slice_of_array is a refrence of orignial array arr

In [28]:
# to actually create a copy:

In [29]:
arr_copy=arr.copy()

In [30]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [32]:
arr_copy[:]=100

In [33]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
# changes made in arr_copy are not reflected to arr

In [38]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [39]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
#method 1- double bracket notation

In [42]:
arr_2d[0][0]

5

In [43]:
arr_2d[0]

array([ 5, 10, 15])

In [44]:
arr_2d[1][1]

25

In [45]:
#method 2- single bracket comma notatiom

In [46]:
arr_2d[1,2]

30

In [47]:
arr_2d[1,1]

25

In [49]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [50]:
#slicing in matrix/2d array.
# :2 means grab everything from starting row upto row 2
# 1: means grab everything from coloumn 1 upto last coloumn

In [51]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [53]:
# conditional selection

In [54]:
arr=np.arange(1,11)

In [55]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
# gives true if value >5 else gives false

In [58]:
bool_arr=arr>5

In [59]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [60]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [61]:
# gives value of only those where bool_arr is true

In [62]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [63]:
arr[arr<3]

array([1, 2])

In [64]:
arr_2d=np.arange(50)

In [67]:
arr_2d=arr_2d.reshape(5,10)

In [68]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [70]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])